<?php
/**
 * MaxSite CMS
 * (c) https://max-3000.com/
 * English translation
 */

return [
	'title' => 'Installing MaxSite CMS',
	'help' => 'Help',
	'folder not found' => 'Directory <code>%1</code> is not found or do not have permission to write',
	'file created' => 'The file <code>%1</code> is created',
	'file is not created' => 'The file <code>%1</code> is not created',
	'error secret key' => 'Unable to get the passphrase from the <code>application/maxsite/mso_config.php</code>. Open it and enter their own passphrase. After this refresh this page in your browser.',
	'db is exists' => 'The database is already installed (file <code>database.php</code>)',
	'go site' => 'Go to website',
	'incorrect post' => 'Incorrect  post-query',
	'incorrect email' => 'Invalid email address',
	'incorrect password' => 'The password is too short. Must be at least 8 characters',
	'incorrect login' => 'Too short username admin. Must be at least 3 characters',
	'incorrect db' => 'Error connecting to database:',
	'ok db' => 'A database connection is successfully established',
	'ok sql' => 'All required sql-queries executed',
	'new site' => 'Your new site has been created:',
	'login data' => 'To enter the data use:',
	'slogin' => 'Login:',
	'spassword' => 'Password:',
	'site maxsite' => 'Support site: https://max-3000.com/',
	'new site maxsite' => 'The new site on MaxSite CMS',
	'table exists' => 'Existing table:',
	'_text1_' => 'Entries for the blog',
	'_text2_' => 'Static page',
	'_text3_' => 'News',
	'_text4_' => 'News of the project',
	'_text5_' => 'Hello World!',
	'_text6_' => 'This is your first post. You can edit or delete it via the admin panel.',
	'_text7_' => 'About the site',
	'_text8_' => 'On this page you can write about your site.',
	'f1' => 'Enter the data for the installation',
	'f2' => 'All fields are required',
	'f3' => 'login...',
	'f4' => 'Login admin',
	'f5' => 'password...',
	'f6' => 'Password (more than 8 characters)',
	'f7' => 'email...',
	'f8' => 'Email',
	'f9' => 'name of the site...',
	'f10' => 'Name of the site',
	'f11' => 'Parameters of the MySQL database',
	'f12' => 'These parameters can be obtained from your host.',
	'f13' => 'database server...',
	'f14' => 'Database server (usually <i>localhost</i>)',
	'f15' => 'user base...',
	'f16' => 'User',
	'f17' => 'user password...',
	'f18' => 'Password',
	'f19' => 'database name...',
	'f20' => 'Database name',
	'f21' => 'table prefix...',
	'f22' => 'Table prefix MaxSite CMS',
	'f23' => 'Done',
	'f24' => 'English letters, numbers and symbols <code>*!?#$-+()._</code>',
];

# end of file
